ScanMyTag/Controllers/QRCodeController.cs
using System;
using System.Collections.Generic;
using System.Drawing;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using ScanMyTag.Data;
using ScanMyTag.Models;
using ScanMyTag.Repository;
using ScanMyTag.Service;

namespace ScanMyTag.Controllers
{
   [Authorize]
    public class QRCodeController : Controller
    {
        private readonly IQRCodeRepository _qrCodeRepository;
        private readonly IUserService _userService;
        
        public QRCodeController(IQRCodeRepository qrCodeRepository,IUserService userService)
        {
            _qrCodeRepository = qrCodeRepository;
            _userService = userService;

        }

        [Route("dashboard")]
        public async Task<ViewResult> DashBoard (bool isSuccess = false)
        {
            var qrCodes = await _qrCodeRepository.GetAllQrCodes();
            if (qrCodes != null)
            {
                return View(qrCodes);
            }
            throw new Exception("Couldn't fetch your tags.");
            
        }

        
        [Route("ContactQR")]
        public IActionResult ContactQRGenerator(string tagName,bool isSuccess = false)
        {
            var model = new ContactQRModel();
            ViewBag.isSuccess = isSuccess;
            ViewBag.tagName = tagName;

            return View(model);
        }



        [HttpPost]
        [Route("ContactQR")]
        public async Task<IActionResult> ContactQRGenerator(ContactQRModel contactQrModel)
        {
            if (ModelState.IsValid)
            {
                int id = await _qrCodeRepository.CreateContactQR(contactQrModel);
                if (id > 0)
                {
                    return RedirectToAction(nameof(ContactQRGenerator), new {isSuccess = true, tagName = contactQrModel.Name});
                }

                return View();
            }
            return View();
        }

        [AllowAnonymous]
        [Route("contact-me/{url}", Name = "contact-me")]
        public async Task<ViewResult> GetScannedQr(string url)
        {
            var result = await _qrCodeRepository.GetContactQrByScanning(url);
            var userId = _userService.GetUserId();

            var isOwner = await _qrCodeRepository.CheckQrOwnership(userId, result.Id);
            
            if(result.Enabled == true || isOwner == true)
                return View(result);

            return View();

        }

        [Route("deleteQr/{id}")]
        public async Task<RedirectToActionResult> DeleteQrById(int id)
        {
           var result = await _qrCodeRepository.DeleteQR(id);
           if (result > 0)
           {
               return RedirectToAction("DashBoard");
           }
           else
           {
               throw new Exception("Couldn't delete your tag.");
           }
        }

        [Route("edittag/{id}")]
        public async Task<IActionResult> EditQr(int id)
        {
            var userId = _userService.GetUserId();
            var qrTag = await _qrCodeRepository.GetQrById(id);
            if (qrTag != null)
            {
                if (qrTag.User.Id == userId)
                {
                    return View(qrTag);
                }
                throw new Exception("Permission Denied.");
            }
            throw new Exception("Couldn't fetch your tag.");
           
        }

        [HttpPost]
        [Route("edittag/{id}")]
        public async Task<IActionResult> EditQr(ContactQRModel contactQr, int Id)
        {
            if (ModelState.IsValid)
            {
                var result = await _qrCodeRepository.UpdateQrTag(contactQr);
                if (result)
                {
                    return RedirectToAction("DashBoard");
                }

                return View();
            }

            return View();
        }


        public async Task<RedirectToActionResult> ChangeQrPrivacy(int Qrid)
        {
            int id = Qrid;
            await _qrCodeRepository.UpdateQrPrivacy(id);
            return RedirectToAction("DashBoard");
        }

    }
}

ScanMyTag/Views/Shared/_Layout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    <link href="~/css/layout.css" rel="stylesheet" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.1/css/all.min.css" integrity="sha512-+4zCK9k+qNFUR5X+cKL9EIR+ZOhtIloNl9GIKS57V1MyNsYpYcUrUeQc9vNfzsWfV28IaLL3i96P9sdNyeRssA==" crossorigin="anonymous" />


    <environment include="Development">
        @*<link href="~/lib/twitter-bootstrap/css/bootstrap.css" rel="stylesheet" />*@
        <link href="~/lib/bootswatch/litera/bootstrap.css" rel="stylesheet" />
        <link href="~/css/global.css" rel="stylesheet" />
        <link href="~/lib/jquery-datetimepicker/jquery.datetimepicker.css" rel="stylesheet" />

    </environment>

    <environment exclude="Development">
        <link rel="stylesheet"
              href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootswatch/lux/bootstrap.css"
              asp-fallback-test-class="sr-only"
              asp-fallback-test-property="position"
              asp-fallback-test-value="absolute"
              integrity=""
              crossorigin="anonymous" />
        <link href="~/css/global.css" rel="stylesheet" />
        <link href="~/lib/jquery-datetimepicker/jquery.datetimepicker.min.css" rel="stylesheet" />
    </environment>

</head>
<body  style="background-color: #1C2833">


   
        
        <div id="mySidenav" class="sidenav">
            <a href="#">Profile</a>
        </div>
        <div id="main">
            <partial name="_header" />
            <div class="centeredItem">
                @RenderBody()
            </div>
               
           
        </div>
        

        
    
    
<script>
    var click = 0;
    function openNav() {
        click += 1;
        if (click === 1) {
            document.getElementById("mySidenav").style.width = "250px";
            document.getElementById("main").style.marginLeft = "250px";
        } else {

            document.getElementById("mySidenav").style.width = "0";
            document.getElementById("main").style.marginLeft = "0";
            click = 0;
        }
    }
</script>
    <environment include="Development">
        <script src="~/lib/jquery/jquery.js"></script>
        <script src="~/lib/jquery-validate/jquery.validate.js"></script>
        <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.js"></script>
        <script src="~/lib/jquery-ajax-unobtrusive/jquery.unobtrusive-ajax.js"></script>
        @*<script src="~/lib/popper.js/cjs/popper.js"></script>*@
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
        <script src="~/lib/twitter-bootstrap/js/bootstrap.js"></script>
        <script src="~/lib/jquery-datetimepicker/jquery.datetimepicker.js"></script>
        <script src="~/lib/moment.js/moment.js"></script>
        <script src="~/js/DateTimePicker.js"></script>
    </environment>

    <environment exclude="Development">
        <script src="~/lib/jquery/jquery.min.js"></script>
        <script src="~/lib/jquery-validate/jquery.validate.min.js"></script>
        <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.min.js"></script>
        <script src="~/lib/jquery-ajax-unobtrusive/jquery.unobtrusive-ajax.min.js"></script>
        @*<script src="~/lib/popper.js/cjs/popper.min.js"></script>*@
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
        <script src="~/lib/twitter-bootstrap/js/bootstrap.min.js"></script>
        <script src="~/lib/jquery-datetimepicker/jquery.datetimepicker.full.js"></script>
        <script src="~/lib/moment.js/moment.js"></script>
        <script src="~/js/DateTimePicker.js"></script>
    </environment>
</body>
</html>

ScanMyTag/Views/Shared/_header.cshtml
    <nav class="navbar navbar-expand-sm navbar-dark  justify-content-end mb-5" style="color: white;background-color: #212F3C;font-family: sans-serif;">
    @*<nav class="vertical-nav" style="color: white;background-color: #212F3C;font-family: sans-serif;">*@
    @*<a class="navbar-brand" href="#"></a>*@
    <span style="font-size: 30px; cursor: pointer" onclick="openNav()">&#9776;</span>
        <div class="container">
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse justify-content-end" id="navbarSupportedContent">
                <ul class="navbar-nav mr-auto text-right">
                   
                    <li class="nav-item">
                        @*<a class="nav-link active" asp-controller="Home" asp-action="Index">Home <span class="sr-only">(current)</span></a>*@
                        <a class="nav-link active" asp-controller="QRCode" asp-action="DashBoard">My Tags</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link active" asp-controller="QRCode" asp-action="ContactQRGenerator">New Tag<span class="sr-only">(current)</span></a>
                    </li>
                    @*<li class="nav-item dropdown">
                        <a class="nav-link active dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            Profile
                        </a>
                        <div class="dropdown-menu mt-2" aria-labelledby="navbarDropdown">
                            <a class="dropdown-item" asp-controller="QRCode" asp-action="DashBoard">DashBoard</a>
                            <a class="dropdown-item" href="#">Another action</a>
                            <div class="dropdown-divider"></div>
                            <a class="dropdown-item" href="#">Something else here</a>

                        </div>
                    </li>*@
                    @*<li class="nav-item">
            <a class="nav-link" asp-controller="Account" asp-action="Register">Register <span class="sr-only">(current)</span></a>
        </li>*@



                </ul>
                <form class="form-inline   justify-content-end">
                    @*<input class="btn btn-outline-warning mr-sm-2" type="button" value="Login">*@
                    <partial name="_loggedInUserInfo" />
                </form>
            </div>
        </div>

    </nav>

ScanMyTag/Views/Shared/_loggedInUserInfo.cshtml
@inject Microsoft.AspNetCore.Identity.SignInManager<UserModel> _signInManager;

@if (_signInManager.IsSignedIn(User))
{

        @*<a class="nav-link active">Hello @User.FindFirst("Name").Value</a>

        <a class="nav-link active" asp-action="Logout" asp-controller="Account">Logout</a>

    <a class="nav-link active" asp-action="ChangePassword" asp-controller="Account">Change password</a>*@


    <div class="dropdown">
        <a class="nav-link dropdown-toggle" style="color: white; font-weight: bold; font-family: sans-serif" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Hello, @User.FindFirst("Name").Value
        </a>
        <div class="dropdown-menu mr-4 mt-2">
            @*<a class="dropdown-item"  asp-controller="QRCode" asp-action="DashBoard">DashBoard</a>
        <div class="dropdown-divider"></div>*@
            <a class="dropdown-item" asp-action="ChangePassword" asp-controller="Account">Change Password</a>
            <div class="dropdown-divider"></div>
            <a class="dropdown-item" asp-action="Logout" asp-controller="Account">Logout</a>
        </div>
    </div>

}
else
{
    <a class="btn btn-outline-primary mr-2" style="color: white" type="button" asp-controller="Account" asp-action="SignIn" asp-route-returnUrl="@Context.Request.Path">Login</a>
    <a class="btn btn-outline-primary" style="color: white" type="button" asp-controller="Account" asp-action="Register">Register</a>
}

ScanMyTag/Views/Shared/_tagThumbnail.cshtml
@model ContactQRModel
    <link href="~/css/Slider.css" rel="stylesheet" />
<div class="box card mb-2 shadow-sm" style="background-color: white">
    <div class="mt-2 mr-1">
        
       
            @*<i class="fas fa-eye float-left"></i>*@
           <label class="switch float-right">
                @{
                    var url = Url.Action("changeQrprivacy", "QRCode", new { Qrid = Model.Id });
                }
                <input type="checkbox" value="@Model.Id" checked="@Model.Enabled" onclick="window.location = '@url'" />
                <span class="slider round"></span>
            </label>
        
    </div>
    <img src="@(string.IsNullOrEmpty(Model.QrCode) ? "/images/noimage.png" : Model.QrCode)" class="img-thumbnail"/>
    @*<div class="card-body">*@
        <div class="ml-1">
            <h6 class="col-12 limitDisplayText"><strong></strong><a asp-route="contact-me" asp-route-url="@Model.Url">@(string.IsNullOrEmpty(Model.Name) ? "Name is not available" : Model.Name)</a></h6>
        </div>
        <div class="justify-content-center m-2">
            <div class="btn-group btn-block btn-group-sm" style="background-color: #212F3C; opacity: 0.7; border-radius: 10px">
                <a type="button" class="btn" style="color: white;" download href="@Model.QrCode" target="new"><i class="fas fa-cloud-download-alt"></i></a>
                <a type="button" class="btn" style="color: white;" asp-controller="QRCode" asp-action="EditQr" asp-route-id="@Model.Id"><i class="far fa-edit"></i></a>
                <button type="button" class="btn" style="color: white;" data-toggle="modal" data-target="#exampleModalCenter@(Model.Id)"><i class="far fa-trash-alt"></i></button>
            </div>
        </div>
    @*</div>*@
</div>


<!--Delete Modal Modal -->
<div class="modal fade" id="exampleModalCenter@(Model.Id)" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLongTitle">Confirm Delete</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                Are you sure you want to delete <strong>"@Model.Name"</strong>  ?
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-primary" data-dismiss="modal">Cancel</button>
                <a type="button" class="btn btn-danger pr-4 pl-4" asp-controller="QRCode" asp-action="DeleteQrById" asp-route-id="@Model.Id" target="new">Delete</a>
            </div>
        </div>
    </div>
</div>
<!-- Delete Modal -->